"""Map Natural Earth ADMIN names to Drawdown country names."""


adminmap = {
        'Akrotiri Sovereign Base Area': 'United Kingdom',
        'Aland': 'Finland',
        'American Samoa': 'United States of America',
        'Anguilla': 'United Kingdom',
        'Aruba': 'Netherlands',
        'Ashmore and Cartier Islands': 'Australia',
        'The Bahamas': 'Bahamas',
        'Bajo Nuevo Bank (Petrel Is.)': None,
        'Baykonur Cosmodrome': 'Kazakhstan',
        'British Indian Ocean Territory': 'United Kingdom',
        'British Virgin Islands': 'United Kingdom',
        'Bermuda': 'United Kingdom',
        'Cabo Verde': 'Cape Verde',
        'Cayman Islands': 'United Kingdom',
        'Clipperton Island': 'France',
        'Republic of the Congo': 'Congo',
        'Coral Sea Islands': 'Australia',
        'Cyprus No Mans Area': 'Cyprus',
        'Czechia': 'Czech Republic',
        'Dhekelia Sovereign Base Area': 'United Kingdom',
        'East Timor': 'Timor-Leste',
        'Falkland Islands': None,
        'Federated States of Micronesia': 'Micronesia (Federated States of)',
        'French Polynesia': 'France',
        'French Southern and Antarctic Lands': 'France',
        'Gibraltar': 'United Kingdom',
        'Guam': 'United States of America',
        'Guernsey': 'United Kingdom',
        'Heard Island and McDonald Islands': 'Australia',
        'Hong Kong S.A.R.': 'Hong Kong',
        'Indian Ocean Territories': None,
        'Isle of Man': None,
        'Ivory Coast': "Côte d'Ivoire",
        'Jersey': 'United Kingdom',
        'North Korea': "Democratic People's Republic of Korea",
        'Kosovo': None,
        'Laos': "Lao People's Democratic Republic",
        'Macedonia': 'The former Yugoslav Republic of Macedonia',
        'Macao S.A.R': None,
        'Montserrat': 'United Kingdom',
        'New Caledonia': 'France',
        'Northern Cyprus': 'Cyprus',
        'Norfolk Island': 'Australia',
        'Northern Mariana Islands': 'United States of America',
        'Pitcairn Islands': 'United Kingdom',
        'Puerto Rico': 'United States of America',
        'Republic of Serbia': 'Serbia',
        'Russia': 'Russian Federation',
        'Saint Barthelemy': 'France',
        'Saint Helena': 'United Kingdom',
        'Saint Martin': None,
        'Saint Pierre and Miquelon': 'France',
        'Scarborough Reef': None,
        'Serranilla Bank': None,
        'Siachen Glacier': None,
        'Sint Maarten': None,
        'Somaliland': 'Somalia',
        'South Georgia and the Islands': 'United Kingdom',
        'South Korea': 'Republic of Korea (South Korea)',
        'Spratly Islands': None,
        'Syria': 'Syrian Arab Republic',
        'Turks and Caicos Islands': 'United Kingdom',
        'United States Minor Outlying Islands': 'United States of America',
        'United States Virgin Islands': 'United States of America',
        'US Naval Base Guantanamo Bay': 'United States of America',
        'Vatican': 'Holy See',
        'Wallis and Futuna': 'France',
        'eSwatini': 'Swaziland',
        }

def lookup(admin):
    """Map the names in the Natural Earth shapefile ADMIN field to names used by Drawdown models."""
    return adminmap.get(admin, admin)


# Taken from Regions-Countries sorting tab of Excel model
region_mapping = {
    "Afghanistan": ["Asia (Sans Japan)"],
    "Akrotiri": None,
    "Aland": None,
    "Aland Islands": None,
    "Åland Islands": None,
    "Albania": ["Eastern Europe"],
    "Algeria": ["Middle East and Africa"],
    "American Samoa": ["Asia (Sans Japan)", "USA"],
    "Andorra": ["OECD90"],
    "Angola": ["Middle East and Africa"],
    "Anguilla": ["Latin America"],
    "Antarctica": None,
    "Antigua and Barbuda": ["Latin America"],
    "Antilles (Netherlands)": ["Latin America"],
    "Argentina": ["Latin America"],
    "Armenia": ["Eastern Europe"],
    "Aruba": ["Latin America"],
    "Australia": ["OECD90"],
    "Austria": ["OECD90", "EU"],
    "Azerbaijan": ["Eastern Europe"],
    "Bahamas": ["Latin America"],
    "The Bahamas": ["Latin America"],
    "Bahrain": ["Middle East and Africa"],
    "Baikonur": ["Eastern Europe"],
    "Bangladesh": ["Asia (Sans Japan)"],
    "Barbados": ["Latin America"],
    "Belarus": ["Eastern Europe"],
    "Belgium": ["OECD90", "EU"],
    "Belize": ["Latin America"],
    "Benin": ["Middle East and Africa"],
    "Bermuda": ["Latin America"],
    "Bhutan": ["Asia (Sans Japan)"],
    "Bolivia (Plurinational State of)": ["Latin America"],
    "Bolivia": ["Latin America"],
    "Bolivia, Plurinational State of": ["Latin America"],
    "Bosnia and Herzegovina": ["Eastern Europe"],
    "Bosnia and Herz.": ["Eastern Europe"],
    "Botswana": ["Middle East and Africa"],
    "Brazil": ["Latin America"],
    "British Indian Ocean Territory": None,
    "British Virgin Islands": ["Latin America"],
    "Virgin Islands, British": ["Latin America"],
    "Brunei Darussalam": ["Asia (Sans Japan)"],
    "Brunei": ["Asia (Sans Japan)"],
    "Bulgaria": ["Eastern Europe", "EU"],
    "Burkina Faso": ["Middle East and Africa"],
    "Burundi": ["Middle East and Africa"],
    "Cambodia": ["Asia (Sans Japan)"],
    "Cameroon": ["Middle East and Africa"],
    "Canada": ["OECD90"],
    "Cape Verde": ["Middle East and Africa"],
    "Cayman Islands": ["Latin America"],
    "Central African Republic": ["Middle East and Africa"],
    "Central African Rep.": ["Middle East and Africa"],
    "Chad": ["Middle East and Africa"],
    "Channel Islands": ["OECD90"],
    "Chile": ["Latin America"],
    "China": ["Asia (Sans Japan)", "China"],
    "Christmas Island": None,
    "Cocos Islands": None,
    "Colombia": ["Latin America"],
    "Comoros": ["Middle East and Africa"],
    "Congo": ["Middle East and Africa"],
    "Congo, the Democratic Republic of the": ["Middle East and Africa"],
    "Republic of the Congo": ["Middle East and Africa"],
    "Cook Islands": None,
    "Costa Rica": ["Latin America"],
    "Côte d'Ivoire": ["Middle East and Africa"],
    "Croatia": ["Eastern Europe", "EU"],
    "Cuba": ["Latin America"],
    "Curaçao": ["Latin America"],
    "Cyprus": ["Eastern Europe", "EU"],
    "Cyprus U.N. Buffer Zone": ["Eastern Europe"],
    "Northern Cyprus": ["Eastern Europe"],
    "Czech Republic": ["Eastern Europe", "EU"],
    "Czech Rep.": ["Eastern Europe", "EU"],
    "Democratic People's Republic of Korea": ["Asia (Sans Japan)"],
    "Dem. Rep. Korea": ["Asia (Sans Japan)"],
    "Korea, Democratic People's Republic of": ["Asia (Sans Japan)"],
    "North Korea": ["Asia (Sans Japan)"],
    "Democratic Republic of the Congo": ["Middle East and Africa"],
    "Dem. Rep. Congo": ["Middle East and Africa"],
    "Denmark": ["OECD90", "EU"],
    "Dhekelia": ["Eastern Europe"],
    "Djibouti": ["Middle East and Africa"],
    "Dominica": None,
    "Dominican Republic": ["Latin America"],
    "Dominican Rep.": ["Latin America"],
    "East Timor": ["Asia (Sans Japan)"],
    "Timor-Leste": ["Asia (Sans Japan)"],
    "Ecuador": ["Latin America"],
    "Egypt": ["Middle East and Africa"],
    "El Salvador": ["Latin America"],
    "Equatorial Guinea": ["Middle East and Africa"],
    "Eq. Guinea": ["Middle East and Africa"],
    "Eritrea": ["Middle East and Africa"],
    "Estonia": ["Eastern Europe", "EU"],
    "Ethiopia": ["Middle East and Africa"],
    "Falkland Islands (Malvinas)": ["Latin America"],
    "Falkland Is.": ["Latin America"],
    "Falkland Islands": ["Latin America"],
    "Faroe Islands": ["OECD90"],
    "Faeroe Is.": ["OECD90"],
    "Fiji": ["OECD90"],
    "Finland": ["OECD90", "EU"],
    "Fr. S. Antarctic Lands": None,
    "French Southern Territories": None,
    "French Southern and Antarctic Lands": None,
    "France": ["OECD90", "EU"],
    "French Guiana": ["Latin America"],
    "French Polynesia": ["OECD90"],
    "Fr. Polynesia": ["OECD90"],
    "Gabon": ["Middle East and Africa"],
    "Gambia": ["Middle East and Africa"],
    "Georgia": ["Eastern Europe"],
    "Germany": ["OECD90", "EU"],
    "Ghana": ["Middle East and Africa"],
    "Gibraltar": ["OECD90"],
    "Greece": ["OECD90", "EU"],
    "Greenland": ["OECD90"],
    "Grenada": None,
    "Guadeloupe": ["Latin America"],
    "Guam": ["OECD90", "USA"],
    "Guatemala": ["Latin America"],
    "Guernsey": ["OECD90"],
    "Guinea": ["Middle East and Africa"],
    "Guinea-Bissau": ["Middle East and Africa"],
    "Guinea Bissau": ["Middle East and Africa"],
    "Guyana": ["Latin America"],
    "Haiti": ["Latin America"],
    "Heard I. and McDonald Is.": None,
    "Heard Island and McDonald Islands": None,
    "Holy See": None,
    "Honduras": ["Latin America"],
    "Hong Kong": ["Asia (Sans Japan)"],
    "Hungary": ["Eastern Europe", "EU"],
    "Iceland": ["OECD90"],
    "India": ["Asia (Sans Japan)", "India"],
    "Indonesia": ["Asia (Sans Japan)"],
    "Iran (Islamic Republic of)": ["Middle East and Africa"],
    "Iran": ["Middle East and Africa"],
    "Iran, Islamic Republic of": ["Middle East and Africa"],
    "Iraq": ["Middle East and Africa"],
    "Ireland": ["OECD90", "EU"],
    "Isle of Man": ["OECD90"],
    "Israel": ["Middle East and Africa"],
    "Italy": ["OECD90", "EU"],
    "Ivory Coast": ["Middle East and Africa"],
    "Jamaica": ["Latin America"],
    "Japan": ["OECD90"],
    "Jersey": None,
    "Jordan": ["Middle East and Africa"],
    "Kazakhstan": ["Eastern Europe"],
    "Kenya": ["Middle East and Africa"],
    "Kiribati": None,
    "Korea": ["Asia (Sans Japan)"],
    "Republic of Korea (South Korea)": ["Asia (Sans Japan)"],
    "Republic of Korea": ["Asia (Sans Japan)"],
    "Korea, Republic of": ["Asia (Sans Japan)"],
    "South Korea": ["Asia (Sans Japan)"],
    "Kosovo": ["Eastern Europe"],
    "Kuwait": ["Middle East and Africa"],
    "Kyrgyzstan": ["Eastern Europe"],
    "Lao People's Democratic Republic": ["Asia (Sans Japan)"],
    "Lao PDR": ["Asia (Sans Japan)"],
    "Laos": ["Asia (Sans Japan)"],
    "Latvia": ["Eastern Europe", "EU"],
    "Lebanon": ["Middle East and Africa"],
    "Lesotho": ["Middle East and Africa"],
    "Liberia": ["Middle East and Africa"],
    "Libya": ["Middle East and Africa"],
    "Liechtenstein": None,
    "Lithuania": ["Eastern Europe", "EU"],
    "Luxembourg": ["OECD90", "EU"],
    "Macao": ["Asia (Sans Japan)"],
    "The former Yugoslav Republic of Macedonia": ["Eastern Europe"],
    "Macedonia": ["Eastern Europe"],
    "Macedonia, the former Yugoslav Republic of": ["Eastern Europe"],
    "Madagascar": ["Middle East and Africa"],
    "Malawi": ["Middle East and Africa"],
    "Malaysia": ["Asia (Sans Japan)"],
    "Maldives": ["Asia (Sans Japan)"],
    "Mali": ["Middle East and Africa"],
    "Malta": ["Eastern Europe", "EU"],
    "Marshall Islands": None,
    "Martinique": ["Latin America"],
    "Mauritania": ["Middle East and Africa"],
    "Mauritius": ["Middle East and Africa"],
    "Mayotte": ["Middle East and Africa"],
    "Mexico": ["Latin America"],
    "Micronesia (Federated States of)": None,
    "Micronesia": None,
    "Micronesia, Federated States of": None,
    "Republic of Moldova": ["Eastern Europe"],
    "Moldova": ["Eastern Europe"],
    "Moldova, Republic of": ["Eastern Europe"],
    "Mongolia": ["Asia (Sans Japan)"],
    "Monaco": None,
    "Montenegro": ["Eastern Europe"],
    "Montserrat": ["Latin America"],
    "Morocco": ["Middle East and Africa"],
    "Mozambique": ["Middle East and Africa"],
    "Myanmar": ["Asia (Sans Japan)"],
    "Namibia": ["Middle East and Africa"],
    "Nauru": None,
    "Nepal": ["Asia (Sans Japan)"],
    "Netherlands": ["OECD90", "EU"],
    "Netherlands Antilles / Curacao": ["Latin America"],
    "New Caledonia": ["OECD90"],
    "New Zealand": ["OECD90"],
    "Nicaragua": ["Latin America"],
    "Niger": ["Middle East and Africa"],
    "Nigeria": ["Middle East and Africa"],
    "Niue": None,
    "Norfolk Island": ["Asia (Sans Japan)"],
    "N. Cyprus": ["Eastern Europe"],
    "Northern Mariana Islands": ["Asia (Sans Japan)", "USA"],
    "Norway": ["OECD90"],
    "Oman": ["Middle East and Africa"],
    "Pakistan": ["Asia (Sans Japan)"],
    "Palau": None,
    "Palestine": ["Middle East and Africa"],
    "Palestine, State of": ["Middle East and Africa"],
    "Panama": ["Latin America"],
    "Papua New Guinea": ["Asia (Sans Japan)"],
    "Paraguay": ["Latin America"],
    "Peru": ["Latin America"],
    "Philippines": ["Asia (Sans Japan)"],
    "Pitcairn Islands": ["Asia (Sans Japan)"],
    "Pitcairn": ["Asia (Sans Japan)"],
    "Poland": ["Eastern Europe", "EU"],
    "Portugal": ["OECD90", "EU"],
    "Puerto Rico": ["Latin America", "USA"],
    "Qatar": ["Middle East and Africa"],
    "Reunion": ["Middle East and Africa"],
    "Romania": ["Eastern Europe", "EU"],
    "Russian Federation": ["Eastern Europe"],
    "Russia": ["Eastern Europe"],
    "Rwanda": ["Middle East and Africa"],
    "Saint Helena, Ascension and Tristan da Cunha": ["Middle East and Africa"],
    "Saint Kitts and Nevis": None,
    "Saint Lucia": None,
    "Saint Pierre and Miquelon": ["OECD90"],
    "Saint Vincent and the Grenadines": None,
    "St. Vin. and Gren.": None,
    "Samoa": ["OECD90"],
    "San Marino": None,
    "Sao Tome and Principe": None,
    "São Tomé and Principe": None,
    "Saudi Arabia": ["Middle East and Africa"],
    "Senegal": ["Middle East and Africa"],
    "Serbia": ["Eastern Europe"],
    "Republic of Serbia": ["Eastern Europe"],
    "Seychelles": None,
    "Siachen Glacier": None,
    "Sierra Leone": ["Middle East and Africa"],
    "Singapore": ["Asia (Sans Japan)"],
    "Slovakia": ["Eastern Europe", "EU"],
    "Slovenia": ["Eastern Europe", "EU"],
    "Solomon Islands": ["OECD90"],
    "Solomon Is.": ["OECD90"],
    "Somalia": ["Middle East and Africa"],
    "Somaliland": ["Middle East and Africa"],
    "South Africa": ["Middle East and Africa"],
    "S. Geo. and S. Sandw. Is.": None,
    "South Georgia and the South Sandwich Islands": None,
    "South Sudan": ["Middle East and Africa"],
    "S. Sudan": ["Middle East and Africa"],
    "Spain": ["OECD90", "EU"],
    "Sri Lanka": ["Asia (Sans Japan)"],
    "St-Martin": ["Latin America"],
    "Saint Martin (French part)": ["Latin America"],
    "Sint Maarten": ["Latin America"],
    "Sint Maarten (Dutch part)": ["Latin America"],
    "Saint Barthélemy": ["Latin America"],
    "Sudan": ["Middle East and Africa"],
    "Suriname": ["Latin America"],
    "Swaziland": ["Middle East and Africa"],
    "Sweden": ["OECD90", "EU"],
    "Switzerland": ["OECD90"],
    "Syrian Arab Republic": ["Middle East and Africa"],
    "Syria": ["Middle East and Africa"],
    "Tahiti": None,
    "Taiwan": ["Asia (Sans Japan)"],
    "Taiwan, Province of China": ["Asia (Sans Japan)"],
    "Tajikistan": ["Eastern Europe"],
    "United Republic of Tanzania": ["Middle East and Africa"],
    "Tanzania": ["Middle East and Africa"],
    "Tanzania, United Republic of": ["Middle East and Africa"],
    "Thailand": ["Asia (Sans Japan)"],
    "Togo": ["Middle East and Africa"],
    "Tokelau": None,
    "Tonga": None,
    "Trinidad and Tobago": ["Latin America"],
    "Tunisia": ["Middle East and Africa"],
    "Turkey": ["OECD90"],
    "Turkmenistan": ["Eastern Europe"],
    "Turks and Caicos Islands": ["Latin America"],
    "Tuvalu": None,
    "Uganda": ["Middle East and Africa"],
    "Ukraine": ["Eastern Europe"],
    "United Arab Emirates": ["Middle East and Africa"],
    "United Kingdom": ["OECD90", "EU"],
    "United States of America": ["OECD90", "USA"],
    "United States": ["OECD90", "USA"],
    "United States Virgin Islands": ["Latin America", "USA"],
    "Virgin Islands, U.S.": ["Latin America", "USA"],
    "Uruguay": ["Latin America"],
    "USNB Guantanamo Bay": None,
    "Uzbekistan": ["Eastern Europe"],
    "Vanuatu": ["OECD90"],
    "Vatican": None,
    "Venezuela (Bolivarian Republic of)": ["Latin America"],
    "Venezuela": ["Latin America"],
    "Venezuela, Bolivarian Republic of": ["Latin America"],
    "Viet Nam": ["Asia (Sans Japan)"],
    "Vietnam": ["Asia (Sans Japan)"],
    "Wallis and Futuna Islands": ["Asia (Sans Japan)"],
    "Wallis and Futuna": ["Asia (Sans Japan)"],
    "West Bank": ["Middle East and Africa"],
    "Western Sahara": ["Middle East and Africa"],
    "W. Sahara": ["Middle East and Africa"],
    "Yemen": ["Middle East and Africa"],
    "Yugoslavia": ["Eastern Europe"],
    "Zambia": ["Middle East and Africa"],
    "Zimbabwe": ["Middle East and Africa"],
}


