"""Map Natural Earth ADMIN names to Drawdown country names."""


adminmap = {
        'Akrotiri Sovereign Base Area': 'United Kingdom',
        'Aland': 'Finland',
        'American Samoa': 'United States of America',
        'Anguilla': 'United Kingdom',
        'Aruba': 'Netherlands',
        'Ashmore and Cartier Islands': 'Australia',
        'The Bahamas': 'Bahamas',
        'Bajo Nuevo Bank (Petrel Is.)': None,
        'Baykonur Cosmodrome': 'Kazakhstan',
        'British Indian Ocean Territory': 'United Kingdom',
        'British Virgin Islands': 'United Kingdom',
        'Bermuda': 'United Kingdom',
        'Cabo Verde': 'Cape Verde',
        'Cayman Islands': 'United Kingdom',
        'Clipperton Island': 'France',
        'Republic of the Congo': 'Congo',
        'Coral Sea Islands': 'Australia',
        'Cyprus No Mans Area': 'Cyprus',
        'Czechia': 'Czech Republic',
        'Dhekelia Sovereign Base Area': 'United Kingdom',
        'East Timor': 'Timor-Leste',
        'Falkland Islands': None,
        'Federated States of Micronesia': 'Micronesia (Federated States of)',
        'French Polynesia': 'France',
        'French Southern and Antarctic Lands': 'France',
        'Gibraltar': 'United Kingdom',
        'Guam': 'United States of America',
        'Guernsey': 'United Kingdom',
        'Heard Island and McDonald Islands': 'Australia',
        'Hong Kong S.A.R.': 'Hong Kong',
        'Indian Ocean Territories': None,
        'Isle of Man': None,
        'Ivory Coast': "Côte d'Ivoire",
        'Jersey': 'United Kingdom',
        'North Korea': "Democratic People's Republic of Korea",
        'Kosovo': None,
        'Laos': "Lao People's Democratic Republic",
        'Macedonia': 'The former Yugoslav Republic of Macedonia',
        'Macao S.A.R': None,
        'Montserrat': 'United Kingdom',
        'New Caledonia': 'France',
        'Northern Cyprus': 'Cyprus',
        'Norfolk Island': 'Australia',
        'Northern Mariana Islands': 'United States of America',
        'Pitcairn Islands': 'United Kingdom',
        'Puerto Rico': 'United States of America',
        'Republic of Serbia': 'Serbia',
        'Russia': 'Russian Federation',
        'Saint Barthelemy': 'France',
        'Saint Helena': 'United Kingdom',
        'Saint Martin': None,
        'Saint Pierre and Miquelon': 'France',
        'Scarborough Reef': None,
        'Serranilla Bank': None,
        'Siachen Glacier': None,
        'Sint Maarten': None,
        'Somaliland': 'Somalia',
        'South Georgia and the Islands': 'United Kingdom',
        'South Korea': 'Republic of Korea (South Korea)',
        'Spratly Islands': None,
        'Syria': 'Syrian Arab Republic',
        'Turks and Caicos Islands': 'United Kingdom',
        'United States Minor Outlying Islands': 'United States of America',
        'United States Virgin Islands': 'United States of America',
        'US Naval Base Guantanamo Bay': 'United States of America',
        'Vatican': 'Holy See',
        'Wallis and Futuna': 'France',
        'eSwatini': 'Swaziland',
        }

def lookup(admin):
    """Map the names in the Natural Earth shapefile ADMIN field to names used by Drawdown models."""
    return adminmap.get(admin, admin)
